# Online IDE configuration (safe to delete)

tasks:
  - before: |
      npm install &
      export MO_DEV_HIDE_URLS=1 # hide Candid UI links
      export PATH="$HOME/bin:$PATH"
      echo 'export PATH="$HOME/bin:$PATH"' >> ~/.bashrc
      sudo apt-get install -q -y libunwind-dev
      sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"
      dfx start --background --emulator --clean
      rustup target add wasm32-unknown-unknown
      npm run setup
    init: |
      npm start
    command: |
      npm start

vscode:
  extensions:
    - dfinity-foundation.vscode-motoko
    - rust-lang.rust-analyzer
    - dfinity-foundation.vscode-motoko
    - esbenp.prettier-vscode
    - bradlc.vscode-tailwindcss
    - lightyen.tailwindcss-intellisense-twin

ports:
  - name: Replica
    port: 4943
    visibility: public
    onOpen: ignore
  - name: Dev Server
    port: 3000
    visibility: public
    onOpen: open-browser
